# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-12-22 08:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Section Name')),
                ('duration', models.IntegerField(blank=True, null=True, verbose_name='Duration')),
                ('cut_off', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Cut Off')),
                ('instructions', models.TextField(blank=True, verbose_name='Instructions')),
                ('max_num_of_questions_attemptable', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Maximum number of questions that can be attempted in the section')),
                ('number_of_sections_to_attempt', models.PositiveIntegerField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='section.Section')),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
            },
        ),
    ]
